language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - phpunit

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master